#!/usr/bin/env sh
# Convenience Cargo wrapper for local development.

SCRIPT_DIR_PATH="$( dirname "$( realpath "$0" )" )"
CARGO_BIN_PATH="$( cd "$SCRIPT_DIR_PATH" && rustup which cargo )"

"$CARGO_BIN_PATH" run --manifest-path="$SCRIPT_DIR_PATH/Cargo.toml" -- "$@"
